@startuml
class User {
    name :String
    email :String
    email_verified_at :Date
    password :String
}

class Project {
    project_url :String
    project_identification :String

}

User "1" -- "*" Project
@enduml
